hr_source_dir: <path to directory of the HR dataset>
lr_source_dir: <path to directory of the LR dataset to be saved>
vsr_save_dir: <path to directory of the VSR-upsampled dataset to be saved>
video_save_path: Null
vsr_model: psrt
spynet_path: Null
vsr_model_path: Null
downscale_factor: 4
subpixel: "bicubic"
white_background: false
als : false
num_images_in_sequence: 100
similarity: 'feature'
thres_values: [45]
lambda_tex: 0.60 
