port: 6010
hr_source_dir: <path to directory of the HR dataset>
lr_source_dir: <path to directory of the LR dataset to be saved>
vsr_save_dir: <path to directory of the VSR-upsampled dataset to be saved>
video_save_path: Null
spynet_path: Null
vsr_model_path: Null
vsr_model: psrt
downscale_factor: 8
upscale_factor: 4
subpixel: "bicubic"
white_background: false
als : true
num_images_in_sequence: 8
similarity: 'pose'
thres_values: [30, 50]
lambda_tex: 0.40 
